#include "gPillar.c"
#include "gPlatform.c"
#include "gStairs.c"
#include "gBishop.c"
#include "gHand.c"
#include "gGate.c"

#include "gPillar_collision.c"
#include "gPlatform_collision.c"
#include "gStairs_collision.c"
#include "gBishop_collision.c"
#include "gHand_collision.c"
#include "gGate_collision.c"